### ISSUE TITLE
Austria und Deutschland integrieren

### ISSUE THREAD

**Issue by sigi2345** [McPringle/pandemieende#1]
Hallo,

Ist es möglich auch Austria und Deutschland einzubinden?

Sigi

**Comment by McPringle** [comment]
Hallo @sigi2345, das gibt es bereits. Einfach etwas nach unten scrollen, dort findest du die Links:
![image](https://user-images.githubusercontent.com/1254039/108988293-96aba200-7694-11eb-94b8-507ee4505d87.png)
