### ISSUE TITLE
pandemieende.de is out-of-date

### ISSUE THREAD

**Issue by laurin** [McPringle/pandemieende#4]
Moin, 
for the last few days, pandemieende.de is always showing 155 days as the time until 70% immunization in Germany.
This is probably because the used `/germany_vaccinations_timeseries_v2.tsv`-file only includes data until `2021-04-16`.
How is this file kept up-to-date? If this is done manually, I would suggested just loading the data straight from `https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv`. 
I'm sorry if I'm in the wrong place for the .de page, is there a seperate repository for that?

**Comment by McPringle** [comment]
Moin Moin

The German page is maintained by Dave, you can reach him at daveloper@pandemieende.at

cu
Marcus
